version: "3"

includes:
  py-std:
    aliases: ["std"]
    taskfile: packages/py-std/
    dir: packages/py-std/
    optional: true # if not found, skip

  better-x:
    aliases: ["bx"]
    taskfile: packages/better-x/
    dir: packages/better-x/
    optional: true # if not found, skip

  bpstd:
    taskfile: packages/bpstd/
    dir: packages/bpstd/
    optional: true #

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  init:env:
    cmds:
      - cp .env.local .env

  install:
    aliases: ["i"]
    cmds:
      - uv sync --all-packages --upgrade

  env:
    cmds:
      - echo "env"
      - echo "ENV1= $UV_PUBLISH_TOKEN"

  uv:
    aliases: ["pkg", "pm"]
    cmds:
      - uv {{.CLI_ARGS}}

  sync:
    cmds:
      # - uv self update
      - uv sync --all-packages --all-groups --upgrade
    ignore_error: true

  fmt:
    cmds:
      # - uv run ruff format . --config=pyproject.toml
      - uv run ruff check --fix . --config=pyproject.toml
      - uv run ruff check --fix . --config=pyproject.toml
      - uv run ruff format . --config=pyproject.toml
      # - uv run ruff format .
    ignore_error: true

  docs:
    cmds:
      - uv sync --all-packages --all-groups
      - uv run mkdocs serve --open --watch=docs --watch=mkdocs.yml --dev-addr=localhost:5004

  docs:deploy:
    aliases: ["docs:d"]
    cmds:
      - task: sync
      - uv run mkdocs gh-deploy # build and create gh-pages branch
      - git push origin gh-pages:gh-pages --force # push to public repo

  build:
    aliases: ["b"]
    cmds:
      - echo "build"
      - uv build
    ignore_error: true

  publish:fix:
    aliases: ["pf"]
    cmds:
      # dist 下文件, _ 改为 -
      - echo "fix dist files"
      - |
        for file in `ls .`; do
          new_file=`echo $file | sed 's/_/-/g'`
          if [ "$file" != "$new_file" ]; then
            echo "rename $file to $new_file"
            mv $file $new_file
          fi
        done
      - open .
    dir: ./dist
    ignore_error: true

  publish:
    aliases: ["pub", "up"]
    cmds:
      # dist 下文件, _ 改为 -
      # - task: publish:fix
      - uv publish
    ignore_error: true

  clean:
    aliases: ["cl"]
    cmds:
      - echo "clean all"
      - rm -rf ./.tox
      - rm -rf ./.pytest_cache
      - rm -rf ./__pycache__
      - rm -rf ./build
      - rm -rf ./dist
      - rm -rf ./*.egg-info
      - rm -rf ./coverage.xml
      - rm -rf ./coverage_html_report
      - rm -rf ./coverage_html_report.zip
    ignore_error: true

  ##################################################################################################

  quick:
    aliases: ["q"]
    cmds:
      - task: cc
      - task: push

  cc:
    cmds:
      - task: commit
      - task: commit

  commit:
    aliases: ["c"]
    cmds:
      - git add .
      - git commit -m "update" --no-verify
    ignore_error: true

  pull:
    cmds:
      - git config pull.rebase false
      - git pull origin main

  push:
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
