version: "3"

includes:
  x:
    taskfile: .task/config/ # by git clone
    dir: .
    optional: true

  better-std:
    aliases: ["std"]
    taskfile: packages/std/
    dir: packages/std/
    optional: true # if not found, skip

  better-px:
    aliases: ["bx", "px"]
    taskfile: packages/px/
    dir: packages/px/
    optional: true # if not found, skip

  bpstd:
    taskfile: packages/bpstd/
    dir: packages/bpstd/
    optional: true #

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  init:env:
    cmds:
      - cp .env.local .env

  install:
    aliases: ["i"]
    cmds:
      - uv sync --all-packages --upgrade

  env:
    cmds:
      - echo "env"
      - echo "ENV1= $UV_PUBLISH_TOKEN"

  dl:
    aliases: ["clone"]
    cmds:
      - mkdir -p .task/
      - |
        git clone --depth=1 \
          https://github.com/better-sre/config.git \
          ./.task/config
    ignore_error: true

  rsync:
    aliases: ["mirror", "mr"]
    cmds:
      - mkdir -p .task/
      - |
        rsync \
          --exclude=".git*" \
          --exclude=".venv" \
          --exclude=".task" \
          --exclude=".github" \
          --exclude=".vscode" \
          --exclude="tmp" \
          --exclude="*.md" \
          --exclude=".env*" \
          --exclude="init.*" \
          --include="*.yml" \
          -avh \
          --progress \
          --no-perms \
          --delete-before \
          --delete \
          ../../better-sre/config/ ./.task/config
    dir: .

  uv:
    aliases: ["pkg", "pm"]
    cmds:
      - uv {{.CLI_ARGS}}

  sync:
    cmds:
      - task: x:py:sync

  fmt:
    cmds:
      - task: x:py:fmt

  new:rs:
    aliases: ["n"]
    cmds:
      # - uv run maturin new --mixed --src {{.CLI_ARGS}} # pyrslib, o3lib
      - uvx maturin new --mixed --src {{.CLI_ARGS}} # pyrslib, o3lib
    dir: packages/

  docs:
    cmds:
      - task: x:py:docs

  docs:deploy:
    aliases: ["docs:d"]
    cmds:
      - task: x:py:docs:d

  build:
    aliases: ["b"]
    cmds:
      - uv build
    ignore_error: true

  publish:fix:
    aliases: ["pf"]
    cmds:
      # dist 下文件, _ 改为 -
      - echo "fix dist files"
      - |
        for file in `ls .`; do
          new_file=`echo $file | sed 's/_/-/g'`
          if [ "$file" != "$new_file" ]; then
            echo "rename $file to $new_file"
            mv $file $new_file
          fi
        done
      - open .
    dir: ./dist
    ignore_error: true

  publish:
    aliases: ["pub", "up"]
    cmds:
      # dist 下文件, _ 改为 -
      # - task: publish:fix
      - uv publish
    ignore_error: true

  clean:
    aliases: ["cl"]
    cmds:
      - task: x:py:cl

  ################################################################################

  count:
    cmds:
      - tokei # 代码统计: https://github.com/XAMPPRocky/tokei

  quick:
    aliases: ["q"]
    cmds:
      - task: cc
      - task: push

  # usage: task rc -- 2
  rc:
    aliases: ["reset:commit"]
    cmds:
      - git reset --soft HEAD~{{.CLI_ARGS}}
      - task: c

  cc:
    cmds:
      - task: commit
      - task: commit

  commit:
    aliases: ["c"]
    cmds:
      - git add .
      - git status
      - |
        git commit -m 'chore: update' --no-verify
    ignore_error: true

  pull:
    cmds:
      - git config pull.rebase false
      - git pull origin main

  push:
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
