[project]
name = "std"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hhglory", email = "hhglory@outlook.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
