version: "3"

tasks:
  env:
    cmds:
      - echo "env"
      - echo "ENV1= $UV_PUBLISH_TOKEN"
    dotenv:
      - ../../.env

  build:
    aliases: ["b"]
    cmds:
      - echo "build"
      - uv build -o dist/
    dir: .
    ignore_error: true

  clean:
    aliases: ["cl"]
    cmds:
      - echo "clean"
      - rm -rf dist
    dir: .
    ignore_error: true

  clean:build:
    aliases: ["cb"]
    cmds:
      - task: clean
      - task: build

  publish:
    aliases: ["pub", "up"]
    cmds:
      - task: build
      - echo "publish to pypi, token is $UV_PUBLISH_TOKEN"
      - uv publish --token $UV_PUBLISH_TOKEN
      - open https://pypi.org/project/better-std/
    ignore_error: true
    dotenv:
      - ../../.env
